# Generated by Django 2.0.7 on 2018-07-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=500)),
                ('article_type', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('article_image', models.ImageField(default='../images/image_001', height_field=100, upload_to='../images/', width_field=100)),
                ('article_desc', models.TextField()),
            ],
        ),
    ]
