# Generated by Django 2.0.7 on 2018-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='../images/image_001', upload_to='../images/'),
        ),
    ]
