# Generated by Django 2.0.7 on 2018-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180712_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='images/image_001', upload_to='images/'),
        ),
    ]
