# Generated by Django 2.0.7 on 2018-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180717_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='images/image_001', upload_to=''),
        ),
    ]
