# Generated by Django 2.0.7 on 2018-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180724_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='arttype',
            name='cover_img',
            field=models.ImageField(default='images/image_001', upload_to=''),
        ),
    ]
